apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Backend.ServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.Backend.ServiceName }}
  ports:
    - protocol: TCP
      port: {{ .Values.Backend.Port }}
      targetPort: {{ .Values.Backend.Port }}
