apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Frontend.ServiceName }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.Frontend.ServiceName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.Frontend.Port }}
      nodePort: 32090
